use_frameworks!

target 'HHCategory-swift_Example' do
  pod 'HHCategory-swift', :path => '../'

  target 'HHCategory-swift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
